version: '3.0'

volumes:
    backend-data:

services:
  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    ports:
      - "5436:5432"
    env_file:
      - .env
    volumes:
      - ./db/sql/:/home

  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/:/code/
      - backend-data:/data
    ports:
      - "8000:8000"
      - "8888:8888"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - '4200:4200'
      - '49153:49153'
    volumes:
      - "./frontend/src:/home/app/client/src"
      - "./frontend/dist:/home/app/client/dist"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true 
      
    
