# Generated by Django 3.0.4 on 2020-07-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200731_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
