# Generated by Django 3.0.4 on 2020-10-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200802_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_number',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
    ]
