code = {
    'OK_LOGIN': 'Login successfully',
    'OK_LOGOUT': 'Logout successfully',
    'OK_REGISTRATION': 'Register successfully',
    'OK_SEND_EMAIL': 'We\'ve just sent you the link to your email',
    'OK_RESET_PASSWORD': 'Reset password successfully',
    'OK_CHANGE_PASSWORD': 'Change password successfully',
    'OK_SEARCH': 'Return search data successfully',
    'OK_UPDATE': 'Update successfully',
    'OK_GET': 'Get successfully',
    'OK_CREATE': 'Create successfully',
    'OK_UPLOAD': 'Upload successfully',
    'OK_DUPLICATE_REQUEST': 'The request is processing',
    'OK_DEACTIVATE': 'Deactivate user successfully',
    'OK_VALID_TOKEN': 'Token is valid',
    'OK_DELETE': 'Delete successful',
    'OK_REQUEST_IS_PROCESSING': 'The request is processing',
    'OK_VALID': 'Information is valid',
    'OK_GRANTED': 'You have been granted to access this repository',
    'E_NOT_ACTIVE': 'Your account is not active',
    'E_LOGIN_INCORRECT': 'The email or password that you entered is incorrect',
    'E_IS_LOGIN': 'You are already log in',
    'E_IS_NOT_LOGIN': 'You are not log in',
    'E_SEND_EMAIL_FAIL': 'There are problems in sending email. Please try again',
    'E_INVALID_PARAMETER_VALUES': 'Request invalid, please verify the parameter',
    'E_USER_NOT_FOUND': 'User can not be found',
    'E_WRONG_PASSWORD': 'Password is incorrect',
    'E_PASSWORD_EXPIRED': 'Password has expired',
    'E_PASSWORD_SAME_WITH_LAST': 'Password must not be the same as your '
                                 'previous password',
    'E_INVALID_ACTIVATE_KEY': 'Your activation key is invalid',
    'E_DUPLICATE_EMAIL': 'The email has been used already',
    'E_DUPLICATE_USERNAME': 'The username has been used already',
    'E_INVALID_EMAIL': 'The email is not valid',
    'E_INVALID_URL': 'URL is not valid',
    'E_INVALID_LOGIN_ID': 'Login id is not valid',
    'E_INVALID_PASSWORD': 'The password must be at least 8 characters long',
    'E_PASSWORD_MISMATCH': 'Password confirmation mismatch',
    'E_LOGIN_MANDATORY': 'The email and password are mandatory',
    'INVALID_TOKEN':'Invalid token'

}