# Generated by Django 3.0.4 on 2020-06-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dbp1',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dbp2',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dbp3',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dbp4',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dbp5',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp1',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp2',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp3',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp4',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp5',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
