# Generated by Django 3.0.4 on 2020-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200705_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='leaf_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='long_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
