# Generated by Django 3.0.4 on 2020-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200705_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='page_type',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
