# Generated by Django 3.0.4 on 2020-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='dbp',
            field=models.CharField(choices=[('dbp1', 'DBP1'), ('dbp2', 'DBP2'), ('dbp3', 'DBP3'), ('dbp4', 'DBP4'), ('dbp5', 'DBP5')], default='DBP1', max_length=4),
        ),
        migrations.AddField(
            model_name='state',
            name='mrp',
            field=models.CharField(choices=[('mrp1', 'MRP1'), ('mrp2', 'MRP2'), ('mrp3', 'MRP3'), ('mrp4', 'MRP4'), ('mrp5', 'MRP5')], default='MRP1', max_length=4),
        ),
    ]
