# Generated by Django 3.0.4 on 2020-06-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default=True, max_length=200, null=True)),
                ('shortDesc', models.TextField(default=True, null=True)),
                ('longDesc', models.TextField(default=True, null=True)),
                ('image', models.CharField(default=True, max_length=200, null=True)),
                ('shortby', models.CharField(default=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeafPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default=True, max_length=200, null=True)),
                ('shortDesc', models.TextField(default=True, null=True)),
                ('longDesc', models.TextField(default=True, null=True)),
                ('image', models.CharField(default=True, max_length=200, null=True)),
                ('shortby', models.CharField(default=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeafType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default=True, max_length=200, null=True)),
                ('shortDesc', models.TextField(default=True, null=True)),
                ('longDesc', models.TextField(default=True, null=True)),
                ('image', models.CharField(default=True, max_length=200, null=True)),
                ('shortby', models.CharField(default=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default=True, max_length=200, null=True)),
                ('shortDesc', models.TextField(default=True, null=True)),
                ('longDesc', models.TextField(default=True, null=True)),
                ('image', models.CharField(default=True, max_length=200, null=True)),
                ('shortby', models.CharField(default=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default=True, max_length=200, null=True)),
                ('shortDesc', models.TextField(default=True, null=True)),
                ('longDesc', models.TextField(default=True, null=True)),
                ('image', models.CharField(default=True, max_length=200, null=True)),
                ('shortby', models.CharField(default=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default=True, max_length=200, null=True)),
                ('shortDesc', models.TextField(default=True, null=True)),
                ('longDesc', models.TextField(default=True, null=True)),
                ('image', models.CharField(default=True, max_length=200, null=True)),
                ('shortby', models.CharField(default=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vechicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default=True, max_length=200, null=True)),
                ('shortDesc', models.TextField(default=True, null=True)),
                ('longDesc', models.TextField(default=True, null=True)),
                ('image', models.CharField(default=True, max_length=200, null=True)),
                ('shortby', models.CharField(default=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VechicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default=True, max_length=200, null=True)),
                ('shortDesc', models.TextField(default=True, null=True)),
                ('longDesc', models.TextField(default=True, null=True)),
                ('image', models.CharField(default=True, max_length=200, null=True)),
                ('shortby', models.CharField(default=True, max_length=200, null=True)),
            ],
        ),
    ]
