# Generated by Django 3.0.4 on 2020-06-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200629_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='longDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='shortDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='shortby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leafposition',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leafposition',
            name='longDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leafposition',
            name='shortDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leafposition',
            name='shortby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leaftype',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leaftype',
            name='longDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leaftype',
            name='shortDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leaftype',
            name='shortby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='longDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='shortDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='shortby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='longDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='shortDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='shortby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='longDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='shortDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='shortby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vechicle',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vechicle',
            name='longDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vechicle',
            name='shortDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vechicle',
            name='shortby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vechiclemodel',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vechiclemodel',
            name='longDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vechiclemodel',
            name='shortDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vechiclemodel',
            name='shortby',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
