# Generated by Django 3.0.4 on 2020-07-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200705_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shipping_ou',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
