# Generated by Django 3.0.4 on 2020-07-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200705_0709'),
        ('accounts', '0004_userprofile_shipping_ou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.State'),
        ),
    ]
