# Generated by Django 3.0.4 on 2021-07-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200725_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sales_channel',
            new_name='company_code',
        ),
    ]
